FROM golang:1.26-alpine AS builder

WORKDIR /src

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /bin/worker ./cmd/worker

FROM alpine:latest

WORKDIR /app

COPY --from=builder /bin/worker /app/worker

EXPOSE 8081

CMD ["/app/worker"]
