FROM golang:1.26-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY cmd/frontend/ cmd/frontend/

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o frontend_bin ./cmd/frontend/main.go

FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /root/

COPY --from=builder /app/frontend_bin .

COPY --from=builder /app/cmd/frontend/templates ./templates

EXPOSE 80

CMD ["./frontend_bin"]
