# Build stage
FROM golang:1.26-alpine AS builder

WORKDIR /src

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies
RUN go mod download

# Copy the source code
COPY . .

# Build the application
RUN CGO_ENABLED=0 GOOS=linux go build -o /bin/manager ./cmd/manager

# Run stage
FROM alpine:latest

WORKDIR /app

# Copy the binary from builder
COPY --from=builder /bin/manager /app/manager

# Expose port
EXPOSE 8080

# Command to run the executable
CMD ["/app/manager"]
