// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/internal/api/worker/hash/crack/task": {
            "post": {
                "description": "Receives a task with hash, max length, alphabet, and partition info, then starts processing asynchronously.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Receive a hash cracking task from the manager",
                "parameters": [
                    {
                        "description": "Task Data",
                        "name": "task",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.WorkerTask"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Task accepted"
                    },
                    "400": {
                        "description": "Invalid request body"
                    }
                }
            }
        }
    },
    "definitions": {
        "models.WorkerTask": {
            "type": "object",
            "properties": {
                "alphabet": {
                    "type": "string"
                },
                "hash": {
                    "type": "string"
                },
                "maxLength": {
                    "type": "integer"
                },
                "partNumber": {
                    "type": "integer"
                },
                "requestId": {
                    "type": "string"
                },
                "totalParts": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Worker Internal API",
	Description:      "This is an internal API for the CrackHash Worker.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
