definitions:
  models.WorkerTask:
    properties:
      alphabet:
        type: string
      hash:
        type: string
      maxLength:
        type: integer
      partNumber:
        type: integer
      requestId:
        type: string
      totalParts:
        type: integer
    type: object
info:
  contact: {}
  description: This is an internal API for the CrackHash Worker.
  title: Worker Internal API
  version: "1.0"
paths:
  /internal/api/worker/hash/crack/task:
    post:
      consumes:
      - application/json
      description: Receives a task with hash, max length, alphabet, and partition
        info, then starts processing asynchronously.
      parameters:
      - description: Task Data
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/models.WorkerTask'
      produces:
      - application/json
      responses:
        "200":
          description: Task accepted
        "400":
          description: Invalid request body
      summary: Receive a hash cracking task from the manager
swagger: "2.0"
